server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: /
    connection-timeout: 5s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 2
        max-attempts: 3
        max-interval: 10000ms
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
          max-interval: 10000ms

  data:
    redis:
      host: ${RDS_HOST}
      port: ${RDS_PORT}
      timeout: 6000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${JWT_SECRET_KEY}
  header: ${JWT_HEADER}

user:
  service:
    base-url: ${USER_SERVICE_BASE_URL}
    timeout: 10s
seller:
  service:
    base-url: ${SELLER_SERVICE_BASE_URL}
    timeout: 10s
cart:
  service:
    base-url: ${CART_SERVICE_BASE_URL}
    timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.amqp: DEBUG