server:
  port: 8081

dotenv:
  enabled: true
  override: true

spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_USERNAME}
    connection-timeout: 5s
    ssl:
      enabled: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 2
        max-attempts: 3
        max-interval: 10000ms
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
          max-interval: 10000ms
  data:
    redis:
      host: ${RDS_REMOTE_HOST}
      port: ${RDS_REMOTE_PORT}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 5000ms
jwt:
  secretKey: ${JWT_SECRET_KEY}
  header: ${JWT_HEADER}

user:
  service:
    base-url: ${USER_SERVICE_BASE_URL}
    timeout: 10s
seller:
  service:
    base-url: ${SELLER_SERVICE_BASE_URL}
    timeout: 10s
cart:
  service:
    base-url: ${CART_SERVICE_BASE_URL}
    timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.amqp: DEBUG